name: flutter_taxcalculate
description: A Dart package for calculating taxes on prices, supporting both inclusive and exclusive tax calculations
version: 1.0.2
repository: https://github.com/gilbert-amo/flutter_taxcalculate

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
